### ISSUE TITLE
Migrate documentation

### ISSUE THREAD

**Issue by logological** [UsenetBig8/STUMP#2]
The documentation currently lives on the [STUMP website](http://igor.chudov.com/stump/). It would be convenient if the documentation were (also) distributed along with the source code.  One way of doing this would be to simply copy the HTML and text files comprising the STUMP website into the `doc` directory, and possibly update the links to make sure they're all relative.  As an alternative, the pages could be converted to Markdown, as this will allow them to be viewed directly on GitHub.

**Comment by logological** [comment]
@tgeek77: Best to hold off on this pending the outcome of our discussions with GNU.  If we end up hosting at Savannah (like most other GNU packages) then Markdown is probably not the best format.

**Comment by logological** [comment]
@tgeek77: Best to hold off on this pending the outcome of our discussions with GNU.  If we end up hosting at Savannah (like most other GNU packages) then Markdown is probably not the best format.

**Comment by logological** [comment]
@tgeek77: Best to hold off on this pending the outcome of our discussions with GNU.  If we end up hosting at Savannah (like most other GNU packages) then Markdown is probably not the best format.

**Comment by tgeek77** [comment]
> @tgeek77: Best to hold off on this pending the outcome of our discussions with GNU. If we end up hosting at Savannah (like most other GNU packages) then Markdown is probably not the best format.

That's what I'm thinking. I'll have the files ready but not uploaded until we know what we'll do next.
